name: raonson
description: Raonson social app
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  flutter_secure_storage: ^9.0.0
  cupertino_icons: ^1.0.6
  video_player: ^2.8.6
  flutter_svg: ^2.0.9
  http: ^1.2.0
  share_plus: ^10.0.2
  shared_preferences: ^2.2.3
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  country_picker: ^2.0.26

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/icon/app_icon.png
    - assets/icons/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon/app_icon.png
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: assets/icon/app_icon.png
