name: raonson
description: Raonson MVP
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #video_player: ^2.8.2

flutter:
  uses-material-design: true
